### ISSUE TITLE
Live Stream Video not showing in search results but url is playable

### ISSUE THREAD

**Issue by jharingkaye** [trizen/pipe-viewer#1]
This video https://www.youtube.com/watch?v=3gOlzV1qEjE does not show up in search results when seaching for the string '4k lofi study music'. For one day, I was able to get around this by setting order to "relevance" and searching for another video before re-inputting the original search string. However, my luck with that has clearly run out and this method is not working anymore. I have attempted to delete the cache directory and config to no avail. However, playing the video by pasting the youtube link does work. I checked and it appears that the code for filtering videos with no time has been commented out. I confirmed this by removing the code and rebuilding the program. (Sorry I'm not a perl developer.) Hope this helps.

**Comment by trizen** [comment]
Thanks for reporting. Fixed [here](https://github.com/trizen/pipe-viewer/commit/0c1d8bf94281251af8460bbd66c72145e656e2a9).
