### ISSUE TITLE
[feature]use emoji instead of asciii symbols

### ISSUE THREAD

**Issue by pirate486743186** [trizen/pipe-viewer#10]
something like this

```
my %symbols = (
               up_arrow    => '👍',
               down_arrow  => '👎',
               diamond     => '💡',
               face        => '😃',
               black_face  => '🤖',
               average     => 'x̄',
               ellipsis    => '🗃️ ',
               play        => '▶️ ',
               views       => '👀',
               heart       => '❤️ ',
               right_arrow => '⏱️ ',
               crazy_arrow => '✨',
               numero      => '#️⃣ ',
              );
```

**Comment by ag-eitilt** [comment]
While I agree that these are quite nice for most cases, I would like to point out that this is even more likely than the previous to break on non-Unicode terminals such as the basic TTYs (yes, there are ways of playing videos on them).  So long as nothing crashes, displaying a "character not found" box is certainly no issue, but it might be helpful to give a way to override symbols in the config, if doing so doesn't add too much complexity.

**Comment by trizen** [comment]
The emoji characters are only used in the Gtk3 version, not in the CLI version.

**Comment by ag-eitilt** [comment]
Ah, I keep forgetting that this repo provides both interfaces.  That does explain why I'd not seen the original characters before either...  Sorry for the false alarm!
