### ISSUE TITLE
Search results appends to the end of previous results in gtk-pipe-viewer

### ISSUE THREAD

**Issue by asakura42** [trizen/pipe-viewer#11]
And no error or warning. So, results not clear and replaced by new results (as gtk-straw-viewer do) but new results appends to the end. It's strange. I use `pipe-viewer-git` from AUR

**Comment by asakura42** [comment]
Ah lol, I see in prefs "clear_search_list" string. I think `1` should be default.

**Comment by trizen** [comment]
The option `clear_search_list` is 1 by default ([source](https://github.com/trizen/pipe-viewer/blob/main/bin/gtk-pipe-viewer#L171)). The option is also controlled by the "Clear search list" in "Other options".

![2021-03-09-081120_1920x1080_scrot](https://user-images.githubusercontent.com/614513/110426651-6275af80-809e-11eb-9909-510e369cbf78.png)
