### ISSUE TITLE
estimate dislikes count

### ISSUE THREAD

**Issue by ghost** [trizen/pipe-viewer#111]
Can't you deduce the dislike count with the up votes and the rating? I'm assuming it's just a simple ratio.

**Comment by benoit-pierre** [comment]
The rating is itself already estimated from the likes / views: see https://github.com/trizen/pipe-viewer/blob/main/lib/WWW/PipeViewer/Utils.pm#L783 and
https://github.com/trizen/pipe-viewer/blob/main/lib/WWW/PipeViewer/Utils.pm#L377.
