### ISSUE TITLE
GUI: After closing the details window and pressing ENTER, it plays the wrong video

### ISSUE THREAD

**Issue by trizen** [trizen/pipe-viewer#126]
GUI: After closing the details window and pressing ENTER, it plays the wrong video.

Steps to reproduce the issue:

1. search for something
2. play any video result
3. select another video result and right-click -> "Show more video details"
4. close the details window
5. press ENTER

Result: it plays the video selected at step 2, instead of the selected video at step 3, which is incorrect.

CC: @benoit-pierre.

**Comment by benoit-pierre** [comment]
Just right clicking on another entry to bring the popup menu would be enough to trigger the issue.
