### ISSUE TITLE
How can I pass video ID as an argument?

### ISSUE THREAD

**Issue by asakura42** [trizen/pipe-viewer#13]
I write mpv addon to use sponsorblock with local database and I need to get video IDs. But I didn't found that option in code. So can I pass video ID as an argument?

**Comment by trizen** [comment]
Do you mean passing the YouTube URL directly to `mpv`?

This can be done by modifying the `mpv` section in the config-file, to:

```perl
 mpv => {
          arg => "--really-quiet *URL*",
          audio => "",
          cmd => "mpv",
          fs => "--fullscreen",
          novideo => "--no-video",
          srt => "--sub-file=*SUB*",
        },
```

**Comment by asakura42** [comment]
Thank you.

**Comment by trizen** [comment]
A small hack to no longer pass the `*URL*` to `mpv`, but still having sponsorblock working:

1. Place [mpv_sponsorblock_minimal](https://codeberg.org/jouni/mpv_sponsorblock_minimal/src/branch/master/sponsorblock_minimal.lua) in `~/.config/mpv/scripts`.
2. Add the following entry in the list of urls:  `"[?&]v=([%w-_]+).*"` inside the function `file_loaded()`

And now in the configuration of `pipe-viewer`, change the `mpv` section to:

```perl
mpv => {
        arg     => "--really-quiet --force-media-title=*TITLE* --no-ytdl *VIDEO*\\&v=*ID*",
        audio   => "--audio-file=*AUDIO*",
        cmd     => "mpv",
        fs      => "--fullscreen",
        novideo => "--no-video",
        srt     => "--sub-file=*SUB*",
       },
```

**Comment by bipox** [comment]
The fix works, but now everything plays at max resolution instead of 720p which I use.

**Comment by trizen** [comment]
> The fix works, but now everything plays at max resolution instead of 720p which I use.

Try [this](https://github.com/trizen/pipe-viewer/issues/13?notification_referrer_id=MDE4Ok5vdGlmaWNhdGlvblRocmVhZDE3NDI3MTAyNzY6NjE0NTEz#issuecomment-1238713964) workaround instead, which allows pipe-viewer to select the resolution.

Otherwise, add in `~/.config/mpv/config` the following line:

```config
ytdl-raw-options-append="format-sort=ext,res:720"
```

**Comment by xsoalokinx** [comment]
Does not appear to be working here for me with pipe-viewer, but works with mpv by itself.
