### ISSUE TITLE
[Feature Request] Add Copy URL option to GTK Pipe & YouTube Viewer context menu

### ISSUE THREAD

**Issue by soonan5** [trizen/pipe-viewer#139]
Hi, first of all thanks for creating this tool. You have saved my old PC! :D

Could you add the `Copy URL` option to the context menu when you right click on a video? Without having to click `Show more details`

![01](https://user-images.githubusercontent.com/109312533/201495330-e879c2de-f7d7-435c-8eb8-dd803d04294a.jpg)

![02](https://user-images.githubusercontent.com/109312533/201495336-cbb40814-f4a8-4406-b403-129ea04629cd.jpg)

**Comment by regexghost** [comment]
Is there a way to copy the URL from terminal `./pipe-viewer`?
