### ISSUE TITLE
GUI: Allow column to be collapsable and change position of the search bar

### ISSUE THREAD

**Issue by antonialoytorrens** [trizen/pipe-viewer#14]
Amazing work you've done! I use this program almost every day on lightweight devices that cannot handle web browsing.

Just a few nitpicks, I'd like more usability on smaller screens.
For example, allowing collapsable columns (I barely use the second column, for _advanced search_), so I'd like to hide it when I don't need it.

Then, the search bar could belong to the first column, as this column should always remain visible, and the search bar should always be accessible.

Here's a small draft to clarify my explanation:
![usability-pipe-viewer](https://user-images.githubusercontent.com/47571676/113493268-2c312180-94de-11eb-8092-0f6a31d7764f.png)

Thank you very much in advance.

**Comment by Kohoshi12** [comment]
This should give a more mobile friendly experience as well. Linux phones are reality now.

**Comment by antonialoytorrens** [comment]
Thank you very much for working on this! I appreciate it a lot! :)
