### ISSUE TITLE
[Feature Request] Add Previous Page in GTK Pipe & YouTube Viewer

### ISSUE THREAD

**Issue by ghost** [trizen/pipe-viewer#141]
So far the only way to see previous videos in GTK is `View > Previous results`. Which doesn't seem very practical. Maybe you can split the Next Page section and add this option! Now consider duplicating this tab and adding it below Thumbnail, Title and Info! This so there is no need to always scroll down to go back or forward.

![01](https://user-images.githubusercontent.com/109312533/201506340-f4fd6ccd-8982-45f7-a419-76929eb149d1.jpg)
![02](https://user-images.githubusercontent.com/109312533/201506344-7116456e-3f72-4b25-ac73-737739af892c.png)
![03](https://user-images.githubusercontent.com/109312533/201506347-4892cec1-4f05-48f9-bf8b-2eb12a1b7d1f.png)

I hope you can add it. And again I thank you for creating this tool, now my computer doesn't crash when watching any YouTube video :D

Blessings!

**Comment by trizen** [comment]
It's also possible to use the side buttons of the mouse.

**Comment by soonan5** [comment]
Mmm... Is this a hidden feature? I'm trying but it doesn't work.

I really wish it could be done graphically, I feel it would be much easier. Ok and how about adding a couple of arrows to be able to go back and forth between the results? Something like the Web Browser.

![ssss](https://user-images.githubusercontent.com/109312533/201516086-b55fe908-1801-415a-a910-a2be6840fee1.png)

**Comment by trizen** [comment]
Implemented in https://github.com/trizen/pipe-viewer/commit/5998e53282dbd613a99fc64f53738a175dfbd937.
