### ISSUE TITLE
[Feature Request] Add Live category in the Author section.

### ISSUE THREAD

**Issue by soonan5** [trizen/pipe-viewer#147]
Some channels have this category. However it is impossible to access it in `CLI` and `GTK`.

![sd](https://user-images.githubusercontent.com/109312533/204755304-553ae819-381f-4af9-9687-c353989e2bf0.png)
![sss](https://user-images.githubusercontent.com/109312533/204755334-1a6d927b-c0b3-41f5-8ff7-ac89f63230b9.jpg)

I also noticed that if you do a search (without considering `Video features`), these videos are filtered out, which allows me to access them for the time being.

![ddd](https://user-images.githubusercontent.com/109312533/204756425-add8b906-1ec2-4729-a98e-8a98e189a120.png)

Could you implement it? Thanks!

**Comment by trizen** [comment]
Added in: https://github.com/trizen/pipe-viewer/commit/6224bb88ae41effb3ef9a3ebc0d4bd6adecbd8c2

I will tag a new version soon.
