### ISSUE TITLE
No support for 144p resolution

### ISSUE THREAD

**Issue by ASWINVENU1** [trizen/pipe-viewer#15]
Hi,
I found both cli and gtk version does not offer 144p support, I don't have experience with perl. However I was able to get 144p suppot on cli version by looking at the code for cli and entering the following line, at line number 1450.

`'144p|8'  => sub { $opt{resolution} = 144 },` 

I could not do this on gtk version. Could you tell me how should I modify the gtk version code to enable 144p resolution support?

**Comment by trizen** [comment]
In the CLI version, there is also the `--resolution=...` option.

Example for setting the resolution to 144p:

```console
pipe-viewer --res=144
```

Additionally, with the above commit, it's also possible to say:

```console
pipe-viewer --144p
```

In the gtk version, the "144p" resolution entry was missing from the menu. Added in the above commit. Thanks for reporting! :)

**Comment by JuPlutonic** [comment]
```
pipe-viewer --res=144
pipe-viewer --144p
resolution                    => "144",
```
gives me no sound!
Thank you.

**Comment by trizen** [comment]
Can you give a video URL for which this happens? Thanks!
