### ISSUE TITLE
Play audio only

### ISSUE THREAD

**Issue by TheChymera** [trizen/pipe-viewer#151]
Is there any way currently to play video audio only? Can I specify that for a series of videos, like `:audio=1..` ?

**Comment by trizen** [comment]
There is the `-n` option. To play multiple results, use either a range (e.g.: `-n 5..10`) or by selecting specific results (e.g.: `-n 1 2 3 4`).

Additionally, to play all the results, including results from the next pages, there is the `-A` option.

To disable the `-n` behavior, we can use `--no-n`.

**Comment by TheChymera** [comment]
@trizen thanks for the reply — is there any way to get a progress bar in audio-only mode? the arrows work for navigation, but it's pretty hard to tell where I am :/ I guess since there's no `mpv` window this might be pretty difficult to implement if it's not already implemented, but e.g. `ncmpcc` (an mpd client I use) has equal signs in the bottom, something like `==========>------------------------------` and I can click on that and navigate.

**Comment by TheChymera** [comment]
Ok, just for reference, that does not output a progress bar, but it gives a `CURRENT_TIME / TOTAL_TIME (PERCENTAGE)` summary. I assume the way it's set up to get a command line progress bar I would need to look into `mpv` since that's what's outputting the current summary.
