### ISSUE TITLE
[Question] How to increase mpv download speed with pipe viewer?

### ISSUE THREAD

**Issue by sun95n** [trizen/pipe-viewer#153]
So YouTube video and audio download speed is limited by ffmpeg as mentioned in this [thread](https://github.com/mpv-player/mpv/issues/8655#issuecomment-1199733728). Although I understand that pipe-viewer manages both URLs separately. So the logical thing to do would be to [pass the URL to mpv](https://github.com/trizen/pipe-viewer/issues/13#issuecomment-809141073) to make it work. The problem is that mpv takes 5-7 seconds to parse a URL unlike pipe-viewer which only takes 2. So is there any other method to achieve this?

**Comment by trizen** [comment]
The solution proposed in [Guidocella's comment](https://github.com/mpv-player/mpv/issues/8655#issuecomment-1199733728), using `yt-dlp` for downloading the streams and piping its standard output to mpv, is very nice and clever.

We can used it in `pipe-viewer`, by adding a new player entry:

```perl
 ytdlp_pipe => {
   arg => "--force-media-title=*TITLE* --audio-file=<(yt-dlp --http-chunk-size 10M -o - *AOV*) <(yt-dlp --http-chunk-size 10M -o - *VIDEO*)",
   cmd => "mpv",
   fs => "--fullscreen",
   novideo => "--no-video",
   srt => "--sub-file=*SUB*",
 },
```

and setting:

```perl
video_player_selected => "ytdlp_pipe",
```

or executing:

```console
pipe-viewer --player=ytdlp_pipe
```

---

The other solution proposed, can be added as:

```perl
 ytdlp_hls => {
     arg => "*URL* --ytdl-format='bestvideo[protocol^=m3u8]+bestaudio[protocol^=m3u8]/bestvideo+bestaudio/best'",
     cmd => "mpv",
     fs => "--fullscreen",
     novideo => "--no-video",
     srt => "--sub-file=*SUB*",
 },
```
