### ISSUE TITLE
Non-youtube content (e.g. odysee, bitchute, peertube)

### ISSUE THREAD

**Issue by TheChymera** [trizen/pipe-viewer#155]
So I've been using `pipe-viewer` for a while and I absolutely love it. Finally liberated from the browser and visual clutter 💛 But there are also good videos on osysee and bitchute — so now these platforms are the lamer ones by comparison, because I have to access them through the browser.

I know the description explicitly states “A lightweight *YouTube* client” so this is probably outside of its scope... but is there any hope to maybe sometime be able to search other platforms as well, or are there some alternative clients you could recommend?

**Comment by trizen** [comment]
For LBRY, there is `lbry-viewer` (fork of `pipe-viewer`): https://github.com/trizen/lbry-viewer

Currently, there are no plans for adding support for other platforms inside `pipe-viewer`.
