### ISSUE TITLE
Mark video as watched in interface

### ISSUE THREAD

**Issue by TheChymera** [trizen/pipe-viewer#157]
Sometimes a video won't show up as watched for some reason (I think maybe I need it to finish for this to happen). Is there any way to quickly mark it as watched in the interface (i.e. other than copying the ID and manually adding it to the watched list)?

Also — and I assume this might not be possible — but maybe something like a percentage can be set, so that videos which I exit if the timer is beyond a certain percentage are auto-marked as watched?

**Comment by TheChymera** [comment]
@sun95n what do you mean by “kind” of videos? In any case I use the CLI so nothing is being “clicked”.

**Comment by trizen** [comment]
In the CLI version, a video is saved to history only after the video player exists with exit-code `0`. This allows pressing `CTRL+C` while watching the video, to prevent the saving of the video to history.

Additionally, I just added in https://github.com/trizen/pipe-viewer/commit/abe65136f9aeb6ea5b6455e7bfddd08f14501f3d the STDIN option: `:w=i`, which saves a video to watch history, without watching the video. More values of `i` can be provided at once, separated by commas.
