### ISSUE TITLE
OAuth login dialog URL doesn't do anything

### ISSUE THREAD

**Issue by binex-dsk** [trizen/pipe-viewer#16]
When logging in, the highlighted OAuth URL for getting an authentication code doesn't work at all. Couldn't find what the URL was supposed to be either

**Comment by trizen** [comment]
This functionality is not implemented (yet) in pipe-viewer. You may want to use [youtube-viewer](https://github.com/trizen/youtube-viewer) for that.

**Comment by binex-dsk** [comment]
On that one, too, when I go to Menu > Login to Youtube, the highlighted URL to get an authentication code doesn't do anything. Do i have to use the `api.json` file?

**Comment by trizen** [comment]
For logging in with `youtube-viewer`, you need an API key and the CLIENT and SECRET tokens, which must be added in `api.json`.

For more info on how to create these keys, see: https://github.com/trizen/youtube-viewer/issues/353#issuecomment-763574106

**Comment by binex-dsk** [comment]
incredible thanks
