### ISSUE TITLE
Searching fails in gtk-pipe-viewer

### ISSUE THREAD

**Issue by rnb42** [trizen/pipe-viewer#165]
Searching for anything fails in gtk-pipe-viewer.
However, updating subscriptions, playing videos, etc. work perfectly fine.
 
The only output I get from gtk-pipe-viewer is this:
```
No results for: example

=>> Previous warnings:
[Wed Mar 29 09:17:08 2023]: No results for: example
```

Maybe something changed on YouTubes' end that broke searching?

**Comment by rnb42** [comment]
In CLI pipe-viewer this problem doesn't exist

**Comment by trizen** [comment]
I can't check at the moment to see what is really going on.

As a possible workaround, try to remove the configuration file of `gtk-pipe-viewer`, or set in the config-file;

```perl
prefer_invidious => 1,
```

**Comment by rnb42** [comment]
I tried this and it sadly didn't fix the issue.

**Comment by IdotMaster1** [comment]
realest

**Comment by trizen** [comment]
Just checked. I cannot reproduce the issue...

**Comment by rnb42** [comment]
it works here again too, very weird
