### ISSUE TITLE
why is this error

### ISSUE THREAD

**Issue by selatinabi** [trizen/pipe-viewer#167]
Hello, why is the error below?

ERROR: Unable to extract uploader id; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

                                                                      Thanks

**Comment by trizen** [comment]
Is an error from `youtube-dl`, failing to extract the channel ID.

Try `yt-dlp` instead.

**Comment by selatinabi** [comment]
Thank you so much for replying.
