### ISSUE TITLE
Pipe-viewer GTK exits on right click

### ISSUE THREAD

**Issue by AidanOreilly** [trizen/pipe-viewer#168]
Arch Linux (all updates installed), XFCE 4.18, pipe-viewer-git 0.4.5.r0.g4af2b90-1.  When right clicking on an entry in list of search results, GTK pipe-viewer exits.  Right clicking on anything else in the GTK pipe-viewer window does not result in this behavior.  Uninstalled, removed config folder, installed clean, behavior persists.

**Comment by benoit-pierre** [comment]
It's a bug with the latest `perl-glib-object-introspection`, fixed on [master](https://gitlab.gnome.org/GNOME/perl-glib-object-introspection/-/commit/e0938b840f7b4aa3884ae2a65d95d8e2202056ed).

**Comment by AidanOreilly** [comment]
Had a hunch it was because of the recent python updates - thx!

**Comment by AidanOreilly** [comment]
Sorry, PERL updates.  Really like this app, BTW... keep up the good work...!!!
