### ISSUE TITLE
[Bug] 0.4.6 broke accelerated downloads.

### ISSUE THREAD

**Issue by sun95n** [trizen/pipe-viewer#169]
Hi @trizen I just downloaded and set up your new release [0.4.6](https://github.com/trizen/pipe-viewer/releases/tag/0.4.6). In the past I had opened an issue (#153) on how to speed up downloads using mpv, the point is that the solution to that problem no longer works in this version.

I tried to solve it from the config files side but unfortunately no success. So I'm afraid it was caused by a commit, since in `0.4.4` and `0.4.5` this doesn't happen.

Thanks for reading and I hope you can fix it :)

**Comment by trizen** [comment]
Hmm... Yeah, I think the new extraction method is throttled more by YouTube.

One workaround would be to set `force_fallback => 1` in the config-file.

**Comment by ryspace** [comment]
Just wanted to chime in to say that this helped me too. After upgrading to the new version, my download speeds were basically making things unbearable. Changed my config to `force_fallback => 1` and it fixed the issue immediately.
