### ISSUE TITLE
Can't apply multiple args to mpv using --append-arg=

### ISSUE THREAD

**Issue by gkytrash** [trizen/pipe-viewer#170]
Trying to use with pipe-viewer with mpv and it won't append more than one arg. I'm trying to use :
mpv --no-border --geometry=0%:100% 

I setup an alias
alias pvm="pipe-viewer --resolution=480p $1 --append-arg=--geometry=0%:100%"

So I can just type "pvm ltt" which works but only for one arg ,it doesn't take multiples

Tried multiple args, arg array. It only takes one arg.

**Comment by trizen** [comment]
Quote the arguments as:

```
--append-arg='--geometry=0%:100% --no-border'
```
