### ISSUE TITLE
"hfr" config option ignored

### ISSUE THREAD

**Issue by tsjnachos117** [trizen/pipe-viewer#172]
Most of my computers are too old for >30 fps videos, so I've been using the "hfr =>0," option in my config file. However, pipe-viewer seems to be ignoring this, and loading 60 fps vids anyway.

My version of pipe-viewer identifies itself as `0.4.5`, althougth I installed it from git. I'm running Ubuntu 22.04, and installed pipe-viewer via makedeb, from the `pipe-viewer-git` package. According to `dpkg`, the version number is `69ace04`, which \*should\* be the git commit it was installed from.

I will upload my `~/.config/pipe-viewer` directory below.
[pipe-viewer_config.tar.gz](https://github.com/trizen/pipe-viewer/files/11641779/pipe-viewer_config.tar.gz)

**Comment by trizen** [comment]
It seems that you have the option `prefer_av1` enabled.

On old computers, try to set:

```perl
hfr        => 0,
prefer_av1 => 0,
prefer_m4a => 1,
prefer_mp4 => 1,
```
