### ISSUE TITLE
select and play video then return to the search result

### ISSUE THREAD

**Issue by jeandestouches** [trizen/pipe-viewer#18]
Hi,
Would it be possible to select & play a video then returns to the search results while keeping the playing video running ?
Currently, when I select & play a video, I have to exit the playing video to return to the results.
This would allow to quickly preload multiple video from a single tab.
Thanks for reading, and thanks for this very useful software.

**Comment by trizen** [comment]
It's possible to use [task-spooler](https://github.com/xenogenesi/task-spooler).

Example:

```perl
                                     mpv => {
                                              arg => "--really-quiet --force-media-title=*TITLE* --no-ytdl *VIDEO*",
                                              audio => "--audio-file=*AUDIO*",
                                              cmd => "tsp mpv",
                                              fs => "--fullscreen",
                                              novideo => "--no-video",
                                              srt => "--sub-file=*SUB*",
                                            },
```

See also: https://youtu.be/I4tfHUmklWo

**Comment by jeandestouches** [comment]
It works just great, thanks for the suggestion. (I only needed to write an ebuild for my Gentoo system, I used regular task-spooler -> https://viric.name/soft/ts/ instead of fork),
I created a new block with "tsmpv" as new "player" as suggested in the video : 

`  video_player_selected         => "tsmpv",
  video_players                 => {
                                     tsmpv => {
                                              arg => "--really-quiet --force-media-title=*TITLE* --no-ytdl *VIDEO*",
                                              audio => "--audio-file=*AUDIO*",
                                              cmd => "ts /usr/bin/mpv",
                                              fs => "--fullscreen",
                                              novideo => "--no-video",
                                              srt => "--sub-file=*SUB*",
                                            },
                                      [...]`

Also, to load multiple video, I set max simultaneous jobs of ts with : 

`ts -S 10`

This way, I can have up to 10 mpv windows opened at the same time. Really cool !

Cheers

**Comment by trizen** [comment]
I'm glad it helped. :)
