### ISSUE TITLE
[solved] Bizarre copy of ARRAY in list assignment

### ISSUE THREAD

**Issue by pirate486743186** [trizen/pipe-viewer#181]
you don't get these errors when launching a video in the gui?
Instead of the entry been marked as read with a color, i get a pop up with the error "Bizarre copy of ARRAY"

```
[Fri Aug 18 20:42:22 2023]: Use of uninitialized value in hash element at /usr/bin/gtk-pipe-viewer line 3265.
[Fri Aug 18 20:42:22 2023]: Bizarre copy of ARRAY in list assignment at /usr/share/perl5/WWW/PipeViewer/Utils.pm line 505.
```

on Debian 12.

**Comment by trizen** [comment]
It seems to be an issue with the Storable Perl module. Maybe the files generated with an older version of perl are no longer compatible with the new version.

Check the above commit to see if it fixes the issue.

If not, try to delete the `.dat` files from `~/.config/pipe-viewer` and `~/.config/pipe-viewer/playlists/`.
