### ISSUE TITLE
feature request: list all past streams for a channel

### ISSUE THREAD

**Issue by incompetentcoder** [trizen/pipe-viewer#183]
Currently when doing :u=channel it only lists uploaded videos but not previous livestreams on youtube, the same for -ls pulling the subscriptions. Not sure how difficult it would be to implement getting streams as well.

**Comment by trizen** [comment]
See the `:streams=i` option.

**Comment by incompetentcoder** [comment]
Ah thank you! I can't find it in --help or --examples or --tricks but works fine thanks!
