### ISSUE TITLE
How to list (current) livestreams of my subscribed channels?

### ISSUE THREAD

**Issue by khlsvr** [trizen/pipe-viewer#185]
I have tried to do this on gkt-pipe-viewer and with pipe-viewer but I can't figure it out.

On gtk-youtube-viewer I can only get to a livestream of one of my subscribed channels at a time and only if I expect it to be live, by going to menu -> subscription videos. Then right-clicking a video by the suspected livestreamer and choose Author->Streams. 
This is best I can get which is, well, x many times less useful than going to https://www.youtube.com/feed/subscriptions on web browser, which shows the livestreams of my subscriptions first on the top.

On pipe-viewer cli client I have tried combining the flags related to livestreams which I have found: `-us`, `--live`, and just the order=upload_date, but I haven't figured out a way to list livestreams from my subscribers. Maybe it's possible so that's why I am asking, thank you.

If it's not possible. Can this feature be added? If not, does anyone know an alternative way (that doesn't require programming from me, small scripts are fine though) for me to quickly get to my livestreams without using the youtube's official website?

**Comment by trizen** [comment]
This is now implemented in https://github.com/trizen/pipe-viewer/commit/2a3df2a472b70084310d83422c9abe8ed2198150 by setting the config-option:

```perl
  subscription_results => "uploads,streams",
```
