### ISSUE TITLE
pipe-viewer --version returns wrong version

### ISSUE THREAD

**Issue by begabba** [trizen/pipe-viewer#189]
I installed the latest AUR package (0.4.8) but running `pipe-viewer --version` returns 0.4.5

yay -S pipe-viewer-git

```
Package (1)      Old Version          New Version          Net Change
pipe-viewer-git  0.4.8.r7.gbfa5a03-1  0.4.8.r7.gbfa5a03-1    0,00 MiB
```

pipe-viewer --version
`CLI Pipe Viewer 0.4.5`

**Comment by trizen** [comment]
Probably you have installed pipe-viewer manually, which gets installed by default in "/usr/bin/site_perl/".

Check:
```
which pipe-viewer
```

It should print "/usr/bin/pipe-viewer". If it prints something else, then delete that file.
