### ISSUE TITLE
login problem

### ISSUE THREAD

**Issue by Nidrop** [trizen/pipe-viewer#19]
nothing happens when i try to login. Search invitation appears again:
```
[user@juser-pc ~]$ pipe-viewer 

=>> Search for YouTube videos (:h for help)
> :login

=>> Search for YouTube videos (:h for help)
> :q
[user@user-pc ~]$ 
```
System: Void Linux
Version: 0.0.9

**Comment by trizen** [comment]
Login support is not implemented (yet?) in `pipe-viewer`.

See also: https://github.com/trizen/pipe-viewer/issues/16

**Comment by rudrrayan** [comment]
Is login support implemented yet @trizen ?

**Comment by trizen** [comment]
> Is login support implemented yet @trizen ?

Nope.
