### ISSUE TITLE
[feature] video_player_selected         => "mpvraw"

### ISSUE THREAD

**Issue by pirate486743186** [trizen/pipe-viewer#191]
i'm proposing having a mpvraw default alternative config. It will be easier for the user to use raw mpv directly by editing the various config options. The motivation for this is sponsorblock, but they are probably others.

something like this, but more properly configured, in the gui and cli.

```
mpvraw => {
               arg   => "--ytdl-raw-options-append=\"format-sort=ext,res:360\" *URL*",
               audio => "--ytdl-format=bestaudio *URL*",
               cmd   => "/usr/bin/mpv",
               fs    => "--fullscreen",
               novideo => "--no-video",
               srt   => "--sub-file=*SUB*",
                     },
```

**Comment by trizen** [comment]
The proposed configuration entry seems to play only the audio.
