### ISSUE TITLE
Sound cuts off the last few seconds of most videos

### ISSUE THREAD

**Issue by andmars** [trizen/pipe-viewer#192]
In most videos I watch the sound cuts off the last 20-40 seconds. It seems the longer the video, the longer the cutoff. (Since I usually watch at 1:33 or 1:46 speeds, I don't know if it happens at normal speed as well).

![20231220_09h27m10s_grim](https://github.com/trizen/pipe-viewer/assets/11244488/87715982-6427-4936-9d51-7e43e1a02391)

**Comment by trizen** [comment]
As a potential workaround for this issue, try setting in the config file:

```perl
split_videos => 0,
```

**Comment by andmars** [comment]
That did the trick and videos seem to load much faster now.

**Comment by andmars** [comment]
That did the trick and videos seem to load much faster now.
