### ISSUE TITLE
gtk-pipe-viewer 0.4.9 does not launch after update from v. 0.4.8

### ISSUE THREAD

**Issue by Balans097** [trizen/pipe-viewer#194]
~$ gtk-pipe-viewer
Unquoted string "state" may clash with future reserved word at /usr/share/perl5/vendor_perl/WWW/PipeViewer/Videos.pm line 145.
Unquoted string "cache" may clash with future reserved word at /usr/share/perl5/vendor_perl/WWW/PipeViewer/Videos.pm line 145.
Operator or semicolon missing before %cache at /usr/share/perl5/vendor_perl/WWW/PipeViewer/Videos.pm line 145.
Ambiguous use of % resolved as operator % at /usr/share/perl5/vendor_perl/WWW/PipeViewer/Videos.pm line 145.
Useless use of modulus (%) in void context at /usr/share/perl5/vendor_perl/WWW/PipeViewer/Videos.pm line 145.
Unquoted string "state" may clash with future reserved word at /usr/share/perl5/vendor_perl/WWW/PipeViewer.pm line 413.
Array found where operator expected (Do you need to predeclare "state"?) at /usr/share/perl5/vendor_perl/WWW/PipeViewer.pm line 413, near "state @LWP_CACHE"
syntax error at /usr/share/perl5/vendor_perl/WWW/PipeViewer.pm line 413, near "state @LWP_CACHE"
Execution of /usr/share/perl5/vendor_perl/WWW/PipeViewer.pm aborted due to compilation errors.
Compilation failed in require at /usr/bin/gtk-pipe-viewer line 56.
BEGIN failed--compilation aborted at /usr/bin/gtk-pipe-viewer line 56.

**Comment by trizen** [comment]
I cannot reproduce this issue with `perl-5.38.1`. Under what version of perl does this issue happen? (`perl -v`)

**Comment by Balans097** [comment]
$ perl -v

This is perl 5, version 38, subversion 2 (v5.38.2) built for x86_64-linux-thread-multi
(with 15 registered patches, see perl -V for more detail)

Copyright 1987-2023, Larry Wall

Perl may be copied only under the terms of either the Artistic License or the
GNU General Public License, which may be found in the Perl 5 source kit.

Complete documentation for Perl, including FAQ lists, should be found on
this system using "man perl" or "perldoc perl".  If you have access to the
Internet, point your browser at https://www.perl.org/, the Perl Home Page.

**Comment by Balans097** [comment]
perl -V

https://pastebin.com/P9wLsdYQ

**Comment by Balans097** [comment]
$ perl -e 'use 5.014; state %x; $x{a}=42; say $x{a}'
42
$ perl -e 'use feature qw(state say); state %x; $x{a}=42; say $x{a}'
42




package WWW::PipeViewer::Videos;

use utf8;
use 5.014;
use warnings;




903d49efb0dd3fd532257b3748bf2a3a934d749e697d3dc53dba37c6a9cae6f7 *Videos.pm
The hash does not match. Could you please provide the correct file. Or what's wrong? I just did «sudo dnf update» yesterday.

**Comment by Balans097** [comment]
And my /usr/share/perl5/vendor_perl/WWW/PipeViewer/Videos.pm contains this:

https://pastebin.com/AdbJFrrS

**Comment by trizen** [comment]
The file matches. Just the line-endings are different (CR-LF vs LF).

However, regarding the issue, maybe there is a bug in the version of `perl` provided by Fedora.

What happens if you try to execute `gtk-youtube-viewer` as:

```
perl $(which gtk-youtube-viewer)
```

Same issue?

There is not much of a difference between v0.4.8 and v.0.4.9. Those `state` statements were in the v0.4.8 as well. I don't think downgrading to v0.4.8 will help. Maybe after the upgrade, `perl` got broken somehow (maybe by a buggy patch applied by the vendor?).

**Comment by Balans097** [comment]
$ perl $(which gtk-pipe-viewer)
Unquoted string "state" may clash with future reserved word at /usr/share/perl5/vendor_perl/WWW/PipeViewer/Videos.pm line 145.
Unquoted string "cache" may clash with future reserved word at /usr/share/perl5/vendor_perl/WWW/PipeViewer/Videos.pm line 145.
Operator or semicolon missing before %cache at /usr/share/perl5/vendor_perl/WWW/PipeViewer/Videos.pm line 145.
Ambiguous use of % resolved as operator % at /usr/share/perl5/vendor_perl/WWW/PipeViewer/Videos.pm line 145.
Useless use of modulus (%) in void context at /usr/share/perl5/vendor_perl/WWW/PipeViewer/Videos.pm line 145.
Unquoted string "state" may clash with future reserved word at /usr/share/perl5/vendor_perl/WWW/PipeViewer.pm line 413.
Array found where operator expected (Do you need to predeclare "state"?) at /usr/share/perl5/vendor_perl/WWW/PipeViewer.pm line 413, near "state @LWP_CACHE"
syntax error at /usr/share/perl5/vendor_perl/WWW/PipeViewer.pm line 413, near "state @LWP_CACHE"
Execution of /usr/share/perl5/vendor_perl/WWW/PipeViewer.pm aborted due to compilation errors.
Compilation failed in require at /usr/bin/gtk-pipe-viewer line 56.
BEGIN failed--compilation aborted at /usr/bin/gtk-pipe-viewer line 56.

> _The value for osvers in perl -V is the version of the kernel that was used to compile perl, which may not match your current kernel version._
I see, thanks. 

> _Maybe after a recent system upgrade, perl got broken somehow (maybe by a buggy patch applied by the vendor?)_
I'll try to reinstall perl. But it is related to the TeXLive that I use. And this is 3.9 GB. But your program is so good that I will still take this radical step.

**Comment by trizen** [comment]
Alternatively, you can compile and install `perl` locally, using [perbrew](https://metacpan.org/pod/App::perlbrew):

```
perlbrew init
perlbrew install --64all -Doptimize='-march=native -O2 -pipe -fno-plt' -j 2 --noman --notest --thread --multi perl-5.38.2
```

Then you can use this local version of `perl` as:

```
perlbrew use perl-5.38.2
```

After installing the required dependencies:

```
cpan -T Gtk3 LWP::Protocol::https
```

You can execute `gtk-pipe-viewer` as:

```
perl -Mlib=/usr/share/perl5/vendor_perl $(which gtk-pipe-viewer)
```

**Comment by trizen** [comment]
I'm using Arch Linux as well, but I'm not getting this error... This is so weird...

Can you please try [this commit](https://github.com/trizen/pipe-viewer/commit/08ef75c682089f08041cae3572dd80ff77564d97) and see if it fixes the issue?

**Comment by Nekosha** [comment]
[That commit](https://github.com/trizen/pipe-viewer/commit/08ef75c682089f08041cae3572dd80ff77564d97) fixed the issue. 

Curiously, I tried an identical installation of Arch (cloned the disk, a few months ago) and it doesn't get this error. I will investigate and report back if I find any clues.

**Comment by trizen** [comment]
Thanks for the testing and confirming the fix.

I guess there is a bug in some of the dependencies; either in `Gtk3`, `Storable`, `Scalar::Util` or `List::Util`, which somehow disable the features enabled by `use 5.014`.

Note: I'm using the latest versions of the dependencies from MetaCPAN (`sudo cpan -u`) and this may explain why I'm not able to reproduce the issue.

**Comment by Balans097** [comment]
trizen man
that helps!
thank you very much!
