### ISSUE TITLE
Comments could not be fetched

### ISSUE THREAD

**Issue by zensubz** [trizen/pipe-viewer#199]
Of late pipe-viewer is unable to display comments for videos. This is the error-msg being displayed if I run gtk-pipe-viewer from the cmdline: `[500 Internal Server Error] Error occurred on URL: https://yt.drgnz.club/api/v1/comments/UzBF_IBNi1o?hl=en-US&sort_by=top`

This issue doesn't happen with gtk-youtube-viewer. Request @trizen to kindly look into this and provide a fix. Thanks in advance!

**Comment by trizen** [comment]
Related to: https://github.com/iv-org/invidious/issues/4566

Try to set `ytdlp_comments => 1` in the config-file, to extract the comments with `yt-dlp`.

**Comment by zensubz** [comment]
Hi @trizen, I tried fetching comments with yt-dlp, and it did work once. But threw the following error for subsequent instances, so I presume that something new is being worked out (as mentioned in iv-org, issue #4566):
`WARNING: [youtube] UzBF_IBNi1o: Cannot decrypt nsig without player_url: You may experience throttling for some formats`.
Closing this issue for now.
