### ISSUE TITLE
dates are displayed incorrectly

### ISSUE THREAD

**Issue by Migacz85** [trizen/pipe-viewer#2]
Like in the title - I'm not sure why is like that.

**Comment by trizen** [comment]
Screenshot?

**Comment by Migacz85** [comment]
I will post output from shell:
CLI Pipe Viewer 0.0.5

```
=>> Select a playlist (:h for help)
> -sp doom emacs

 1. DoomCasts: Emacs Doom Screencasts (by Zaiste Programming) [30 December 2020] [25]
 2. doom-emacs (by Jesse Cho) [30 December 2020] [6]
 3. Doom Emacs Tutorials (by Chris B) [30 December 2020] [7]
 4. The Church of Emacs (by DistroTube) [30 December 2020] [20]
 5. doom-emacs (by Yeong Sheng Tan) [30 December 2020] [11]
 6. Emacs - Doom (by Scott Wade) [30 December 2020] [7]
 7. Emacs Doom (by Klaus Guenter) [30 December 2020] [15]
 8. Emacs Doom (by Felipe Costa) [30 December 2020] [26]
 9. Distrotube-Vims and Emacs(PROPER ORDER) (by JON) [30 December 2020] [17]
10. Emacs stuff (by Kristofer Andersson) [30 December 2020] [40]
11. emacs (by an93lofdeath) [30 December 2020] [25]
12. Emacs Best videos (by Sacha Muszlak) [30 December 2020] [11]
13. emacs (by Zac Ioannidis) [30 December 2020] [6]
14. Programmer Workflow (by Jack of Some) [30 December 2020] [7]
15. emacs (by brcomm) [30 December 2020] [7]
16. EMACS (by Markus Portenier) [30 December 2020] [7]
17. emacs (by Anton Rich) [30 December 2020] [50]
18. Emacs (by Jochen Burkhard) [30 December 2020] [25]
19. Emacs (by John Austin) [30 December 2020] [25]
20. emacs (by Null Pointer) [30 December 2020] [6]

=>> Select a playlist (:h for help)

```

**Comment by trizen** [comment]
That's because YouTube does not say when a playlist was created in search results:

https://www.youtube.com/results?search_query=test&sp=EgIQAw%253D%253D

I will adjust the results in the near future to exclude the incorrect date. Thanks for reporting.

**Comment by Migacz85** [comment]
Ok, I can understand that -but when I play video from playlist it said:

=> URL: https://www.youtube.com/watch?v=rCMh7srOqvw
-> Channel   : Zaiste Programming
-> ChannelID : UCzgkOWKcwy0uhYilE6bd1Lg
-> VideoID   : rCMh7srOqvw
-> Duration  : 07:03
-> Published : 30 December 2020

and this date is also wrong.

**Comment by trizen** [comment]
`pipe-viewer` doesn't currently parse the YouTube video page (which indeed includes the correct date of the video), but probably it should do that. However, this would increase the start-up time for videos a little bit, as it would require an extra GET request, so it will be a sensible trade-off...

**Comment by Migacz85** [comment]
Ok, it would be nice to at least give some flag to enable this extra GET
request. What do you think?

**Comment by trizen** [comment]
Fixed in: https://github.com/trizen/pipe-viewer/commit/d7a6aa379fb25a87ae23e9b734487b1afcce07fd
