### ISSUE TITLE
[Bug] : YouTube shorts not being loaded either in Channel view or Results

### ISSUE THREAD

**Issue by IkelAtomig** [trizen/pipe-viewer#201]

**Comment by trizen** [comment]
See the `--shorts=CHANNEL_ID` option, or `:shorts=i` in interactive mode.

**Comment by IkelAtomig** [comment]
Sorry, I meant it on the `gtk-pipe-viewer`.

**Comment by trizen** [comment]
Right click on a video -> Author -> Shorts.

**Comment by IkelAtomig** [comment]
![Screenshot 7](https://github.com/trizen/pipe-viewer/assets/101938856/67b45e3e-1e28-4f2f-87c8-b465038733c0)

**Comment by trizen** [comment]
Ah, there were some YouTube changes. Should be fixed now in https://github.com/trizen/pipe-viewer/commit/6f692afe25530d6568e8763c3d468224ee131afd.

**Comment by IkelAtomig** [comment]
Does it also fix Livestreams too not showing in the feed or are they excluded from it ?

**Comment by trizen** [comment]
YouTube splits the videos into three categories: regular videos, livestreams and shorts. In feeds, only regular videos are displayed.

Perhaps there should be an option to include livestreams as well?

**Comment by IkelAtomig** [comment]
I would say why not, it would be easy to manage feed consumption that way.
