### ISSUE TITLE
[serious bug] "show more details" in fullscreen blocks the app

### ISSUE THREAD

**Issue by pirate486743186** [trizen/pipe-viewer#202]
if you try  "show more details" in fullscreen, the new window isn't visible, but you can't interact with the main window any more, so you seam completely stuck. You can get unstuck by pressing "esc" to close the not visible details window, but not all users know about this.

**Comment by trizen** [comment]
I cannot confirm this issue on Openbox. It may be an issue related to your Desktop Environment or Window Manager.
