### ISSUE TITLE
Can I change the fps of the video from 60 to 30 fps?

### ISSUE THREAD

**Issue by Sijelo** [trizen/pipe-viewer#208]
I want to watch videos in 720p, but at 30 fps. I looked for an option to change the fps in the settings, but you can only change the codec and resolution. I also tried using hfr at 0, but when I do that I'm limited to 480p.

**Comment by trizen** [comment]
This is possible by setting `hfr => 0,` in the config-file. However, some videos only have 720p and higher resolutions available at 60fps, which is why the resolution may be lowered at 480p.
