### ISSUE TITLE
Either freeze or no results warning when trying to search videos

### ISSUE THREAD

**Issue by AnErrupTion** [trizen/pipe-viewer#22]
So basically, everything is in the title. I've tried removing the configuration files but it didn't work, and it seemed to work fine before. I'm using `pipe-viewer-git` from the chaotic-aur, and its version is 0.0.9 so the current latest.

**Comment by trizen** [comment]
I cannot confirm this issue...

Execute `pipe-viewer --debug test` to see what it's going on.

If there is an issue connecting to `m.youtube.com`, pass the `--invidious` argument (or set `prefer_invidious` to `1` in the config file), which will use an invidious instance to get the YouTube results.

**Comment by pirate486743186** [comment]
sounds like a bad internet connection
or blocked invidious instance.
