### ISSUE TITLE
youtube comments

### ISSUE THREAD

**Issue by pirate486743186** [trizen/pipe-viewer#23]
invidius instances are blocked most of the time
so most of the time you get nothing....

~~may i suggest this little python application
https://github.com/egbertbouman/youtube-comment-downloader~~

~~it downloads youtube comments without using the API, in JSON.
It should be very helpful.~~

EDIT: yt-dlp is beater.

**Comment by pirate486743186** [comment]
yt-dlp can download comments as json. It's a bit convoluted, for example:

`yt-dlp --write-comments --extractor-args "youtube:comment_sort=top;max_comments=3;max_comment_depth=1" --skip-download https://www.youtube.com/watch?v=5_4TKRgEr9U`

documentation for extractor arguments for youtube
https://github.com/yt-dlp/yt-dlp#extractor-arguments

an extra extractor argument will probably be added.
https://github.com/yt-dlp/yt-dlp/issues/1390

**Comment by trizen** [comment]
Experimental support for extracting YouTube comments with `yt-dlp` (disabled by default) has been added in: https://github.com/trizen/pipe-viewer/commit/f29047ca36a55456fa19c1cb33309443dba7a2ac
