### ISSUE TITLE
[UI] show more details

### ISSUE THREAD

**Issue by pirate486743186** [trizen/pipe-viewer#24]
In the "show more details" window.
Can you split the column of details into two columns and leave more room for the description?

**Comment by pirate486743186** [comment]
This is not just cosmetic.
i have bad eye site, so the fonts  are inflated and my screen is a bit small.
If i just maximize the window, i still can't read the description.

**Comment by trizen** [comment]
The "Extra details" window has a vertical pane (resize bar) that allows more room for the description.

![sshot](https://user-images.githubusercontent.com/614513/120915976-55b12980-c696-11eb-96ef-cad7a6d0123e.jpg)

**Comment by pirate486743186** [comment]
yea, that's ok.

Under the default mate theme in 18.04 the line is invisible....
But that's the themes fault.
