### ISSUE TITLE
Options -ls doesn't show any video

### ISSUE THREAD

**Issue by bagnacauda** [trizen/pipe-viewer#29]
Thank you by the way for implementing offline subscriptions, it is very much appreciated.

The behavior is very simple to explain: you can save channels using `:save=i`, and they show up using `-lc`, but `-ls` doesn't show anything at all, unlike youtube-viewer.

**Comment by bagnacauda** [comment]
The message I get by the way is:
```[!] No subscribed channels...```

**Comment by trizen** [comment]
Use `:sub=i` to subscribe to a channel. Subscribed channels can be listed with `-S`.

Option `:save=i` is used just for saving channels in `-lc`, but without subscribing to them.

**Comment by bagnacauda** [comment]
Thank you, I just read [this](https://github.com/trizen/youtube-viewer/commit/6137ee3cfecb552b8e83fc1a65797c689d6afb19) and I assumed it would be the same over here.
