### ISSUE TITLE
Offline subscription mechanism

### ISSUE THREAD

**Issue by bagnacauda** [trizen/pipe-viewer#3]
Right now :subscription seems to require the login, but if I do :login nothing happens. It would be nice to have :subscription to subscribe only in an offline manner, in a JSON file or whatnot. Also :login seems out of place since this version of the app does not make use of the YouTube APIs from what I can understand.

**Comment by BridgetX** [comment]
This would be very good, would also be nice if the program, just like NewPipe, could accept Youtube's export files to instantly add all of your subscriptions, without the need to login or do each one of them manually.

**Comment by trizen** [comment]
I recently added support for subscription videos in youtube-viewer (without requiring authentication): https://github.com/trizen/youtube-viewer/commit/6137ee3cfecb552b8e83fc1a65797c689d6afb19

A similar approach can be added to pipe-viewer as well. Maybe in the near future.

**Comment by trizen** [comment]
Added in version 0.1.0: https://github.com/trizen/pipe-viewer/releases/tag/0.1.0
