### ISSUE TITLE
Video Review

### ISSUE THREAD

**Issue by wiwikuan** [trizen/pipe-viewer#30]
Hi, I'm the guy who made this video review:

[CN] Pipe-viewer！有史以來最佳的 YouTube 體驗就在這裡～
https://wiwi.video/videos/watch/798d38cd-9d10-4f8a-ac1f-f776c6d0aa2c

Thank you for including my video in your README, but I'm from Taiwan, not China. May I request that you change the [CN] to [TW]? Thanks a lot!

**Comment by trizen** [comment]
Changed. Thanks for reporting. Also thank you for the video review. :)
