### ISSUE TITLE
[QUESTION]: How to use absolute paths to referenced programs?

### ISSUE THREAD

**Issue by raghavgururajan** [trizen/pipe-viewer#33]
I am [packaging pipe-viewer](https://issues.guix.gnu.org/49210) into [Guix](https://guix.gnu.org).

The programs ffmpeg, mpv, wget, xdg-open, and youtube-dl; are referenced in the files bin/pipe-viewer, bin/gtk-pipe-viewer, and lib/WWW/PipeViewer.pm.

IIUC, the application tries to find these programs in $PATH (as if they were installed explicitly in the system). Guix works in a different way. If the app were to be run in a pure environment or in container, the app can only have access to specific things. Other things installed in system are not accessible to the app.

So I am trying to replace those references (program) with absolute references (/path/to/program). I tried replacing the occurrences of 'program' and "program", to '/path/toprogram' and "/path/to/program", respectively; in the files bin/pipe-viewer, bin/gtk-pipe-viewer, and lib/WWW/PipeViewer.pm.

But I still get this error:
```
Can't exec "youtube-dl": No such file or directory at /gnu/store/k8c3019fvagc89rsm1qz87p6f4m9mnyj-pipe-viewer-0.1.2/lib/perl5/site_perl//5.30.2/WWW/PipeViewer.pm line 1489.
sh: mpv: command not found
```

Could anyone please help me with what is wrong and how to correct it?

Regards,
RG.

**Comment by trizen** [comment]
To hardcode the paths to `mpv` and `youtube-dl`, replace `undef` with `"/path/to/program"` in ([#L277](https://github.com/trizen/pipe-viewer/blob/main/bin/pipe-viewer#L277))

```perl
ytdl_cmd => undef,     # auto-defined
```

and ([#L185](https://github.com/trizen/pipe-viewer/blob/main/bin/pipe-viewer#L185))

```perl
    video_player_selected => (
        $constant{win32}
        ? 'vlc'
        : undef    # auto-defined
    ),
```

**Comment by raghavgururajan** [comment]
@trizen 

Thank you!
