### ISSUE TITLE
mpv-sponsorblock with pipe-viewer

### ISSUE THREAD

**Issue by Dynexyst** [trizen/pipe-viewer#37]
I need to use *URL* instead of *VIDEO* to have mpv sponsorblock work.
With *URL*, pipe-viewer doesn't tell mpv the resolution to use so you would have to configure that manually.
--ytdl-format='bestvideo[height<=*RESOLUTION*]+bestaudio/best[height<=*RESOLUTION*]'
This would work if *RESOLUTION* returned just the vertical height of the video [720] and not the height with a p [720p].

**Comment by trizen** [comment]
See: https://github.com/trizen/pipe-viewer/issues/13

**Comment by Dynexyst** [comment]
Yeah, that seems to work. This does not allow for changing the resolution inside of pipe-viewer though. If \*RESOLUTION\* returned just the number like i explained in my previous comment, you could add a --ytdl-format argument into the mpv section of the pipe-viewer config and have it play the desired format.

**Comment by trizen** [comment]
I now see what you're saying. Changed in: https://github.com/trizen/pipe-viewer/commit/169762ddce654368f3c503bf84a9aa6702d76358
