### ISSUE TITLE
pipe-viewer doesn't know it's up to date

### ISSUE THREAD

**Issue by SlidingHorn** [trizen/pipe-viewer#41]
Any time I attempt to watch a video, I get the following:

```
WWW::PipeViewer version v0.1.4 required--this is only version v0.1.3 at /usr/bin/pipe-viewer line 49.
BEGIN failed--compilation aborted at /usr/bin/pipe-viewer line 49.
```

I am running the latest version from the AUR `-git` package.

```
pacman -Qi pipe-viewer-git
Name            : pipe-viewer-git
Version         : 0.1.4.r0.gc999250-1
```

**Comment by trizen** [comment]
Maybe you installed `pipe-viewer` manually before?

Check to see if the following file exists:

```
/usr/share/perl5/site_perl/WWW/PipeViewer.pm
```

If it does exist, then remove it, along with the following directory:

```
/usr/share/perl5/site_perl/WWW/PipeViewer
```

The version from the AUR is installed under `/usr/share/perl5/vendor_perl/WWW/PipeViewer`.

**Comment by SlidingHorn** [comment]
It was there....should I rebuild my AUR package, or should I just "grip it & rip it"?
