### ISSUE TITLE
Reverse sorted playlist - how to handle them ?

### ISSUE THREAD

**Issue by stacyharper** [trizen/pipe-viewer#44]
Hello there !

First of all, thanks a lot for this software that rock.

Sometime a playlist is ordered from newest to oldest. To play them I can see two options:

- Add a command to reverse a searched list of results
- Allow to ..1 that would mean "last to first" (similary to 1.. "first to last")

Is there already a way to handle those cases and I missed it ? Those solutions are conceivablle ?

Thanks a lot !

**Comment by trizen** [comment]
Hi. For playing the results in reverse order, there are two options already available:

* `-B` will play all the results from the last one to the first
* `20..1` will play the selected range of videos in reverse order

Sorry for the late reply.
