### ISSUE TITLE
[feature] gui improvements when lauching a video

### ISSUE THREAD

**Issue by pirate486743186** [trizen/pipe-viewer#45]
It would be nice to have a visual cue, that you indeed launched the video. For example, the block of the video in the list could blink when it starts launching the video. (hmm, is it just slow, or i didn't press the button well enough?)

It would be nice, to immediately fork a new process when starting a video. For example, the cli app is forked, that then launches the video. This prevents the gui from freezing while it does its thing. I mean, this would be hidden from the user, not launching it with xterm. forking the cli app, would be the simplest way to do it.

**Comment by benoit-pierre** [comment]
#103 took care of not freezing the GUI, and #130 takes care of the visual cue.
