### ISSUE TITLE
extreamly slow when opening a video

### ISSUE THREAD

**Issue by Migacz85** [trizen/pipe-viewer#49]
Also the video streaming is super slow. It buffer for a minute then play video for 5 sek. Internet is fine. Videos on yt are opening super fast.

What is going on? Hm...

**Comment by trizen** [comment]
The throttling issue should be fixed in version 0.1.5 (https://github.com/trizen/pipe-viewer/commit/45d07fc66bc8b1031d30f02ac09b302a3fdab343). What version are you using?

**Comment by Migacz85** [comment]
CLI Pipe Viewer 0.0.5

**Comment by Migacz85** [comment]
Ok i reinstaled it using `yay` - it's working as expected.
