### ISSUE TITLE
unsupported webp thumbnails

### ISSUE THREAD

**Issue by pirate486743186** [trizen/pipe-viewer#50]
In "show more details", often i don't see the thumbnails.
I think, the underlying libraries don't support webp.

i'm getting this error (debian 11, 32bits):
`Image type “webp” is not supported at /usr/lib/i386-linux-gnu/perl5/5.32/Glib/Object/Introspection.pm line 67.`

Either it's a missing dependency, or it needs a conversion.
Probably, it should first try to load them as is, then fallback in converting them.
This way it's future/back proofed.

**Comment by trizen** [comment]
The "webp-pixbuf-loader" library is needed. I think I will change gtk-pipe-viewer to always use JPEG thumbnails for now, as this library seems to not be available on the Ubuntu and Debian repos.

**Comment by pirate486743186** [comment]
just mentioning how to install webp-pixbuf-loader for when you'll reactivate the feature.

For ubuntu, you need to add this ppa, then install the library as usual
`sudo add-apt-repository ppa:krifa75/eog-ordissimo`
`sudo apt update`
`sudo apt install webp-pixbuf-loader`

for debian(ubuntu), there's a source package that you need to build your self.
it's from https://salsa.debian.org/okias-guest/webp-pixbuf-loader this is from debian maintainers, as of writing, it hasn't reached repositories yet.

you can download the source package like this:
`git clone https://salsa.debian.org/okias-guest/webp-pixbuf-loader.git`

then install needed stuff for building packages in general:
`sudo apt install build-essential dpatch fakeroot devscripts equivs lintian quilt`

install build dependencies for this package (it will create a metapackage for them)
`sudo mk-build-deps -i -r webp-pixbuf-loader/debian/control`

build the package
`fakeroot webp-pixbuf-loader/debian/rules binary`

you can install it with apt as usual (you need to give apt, the full path to a local package file) for example, a package in the current directory:
`sudo apt install ./webp-pixbuf-loader_0.0.3-1_i386.deb`
