### ISSUE TITLE
"undefined value as a HASH reference" when I have a lot of subscriptions [Manjaro Linux]

### ISSUE THREAD

**Issue by zeronobody0** [trizen/pipe-viewer#51]
I have a lot of subscriptions, so I wasn't surprised that going to Menu>Subscription Videos took a while to load, but I didn't expect an error. The error is below. Thank you for your time.
> Can't use an undefined value as a HASH reference at /usr/share/perl5/vendor_perl/WWW/PipeViewer/InitialData.pm line 516

**Comment by trizen** [comment]
I think this happens for a deleted channel. Or when the channel ID is incorrect.

**Comment by zeronobody0** [comment]
Please add something to the error message that tells the user which channel (as identified by the name next to the ID) has an incorrect ID/is deleted?
