### ISSUE TITLE
The command line parameters/config options had no effects.

### ISSUE THREAD

**Issue by ZaxonXP** [trizen/pipe-viewer#57]
Using version 0.1.7

1. Tried to use the `--results=50` but the `pipe-viewer` always shows 20 results.
2. I set up the `maxResults=50` which shows correctly when I use `--help`, but has no effect on the results displayed (still 20).
3. Tried to use `--page=x` (where x was 2, 3, 4, 5), but only first page was always displayed.

Why do I have such issues?

Kind regards,
Piotr

**Comment by trizen** [comment]
Currently, the `--page=i` and `--results=i` options only apply to displaying videos from the local playlists. 

Example:

```console
$ pipe-viewer --watched-videos --results=50
$ pipe-viewer --watched-videos --results=10 --page=2
```

Extending them to YouTube search results is not a trivial task, as the web-interface of YouTube does not offer these options.

**Comment by ZaxonXP** [comment]
But it is interesting that I get next pages of results when I press `enter` being in the `pipe-viewer` interactive interface.
