### ISSUE TITLE
hide terminal in GTK application [Feature]

### ISSUE THREAD

**Issue by rudrrayan** [trizen/pipe-viewer#58]
I was wondering whether the terminal could be hidden when using the GTK version of pipe viewer, when the "audio only" option is enabled. It would be very useful and (I think?) not too difficult to pull off. thanks in advance,

**Comment by trizen** [comment]
Using [Tilix](https://github.com/gnunn1/tilix), set this in the configuration file of `gtk-pipe-viewer`:

```perl
  terminal                    => "/usr/bin/tilix",
  terminal_exec               => "--minimize -e '%s'",
```

The terminal will start as minimized.
