### ISSUE TITLE
AUR packaging issue

### ISSUE THREAD

**Issue by asakura42** [trizen/pipe-viewer#64]
>rm: cannot remove '/home/asakura/.config/trizen/sources/pipe-viewer-git/pkg/pipe-viewer-git/usr/lib': No such file or directory

Maybe recent git version has some differences with g6b7cb0a described in PKGBUILD? I didn't tried to fix it, maybe you know what to do.

**Comment by trizen** [comment]
I can't reproduce this issue...

**Comment by asakura42** [comment]
😑 I'll try to reproduce it with another system and AUR helpers and post here.

**Comment by asakura42** [comment]
Haha, `unset PERL_LOCAL_LIB_ROOT PERL_MM_OPT PERL_MB_OPT` fixed issue.
