### ISSUE TITLE
pipe-viewer/lbry-viewer PKGBUILD for debian

### ISSUE THREAD

**Issue by ghost** [trizen/pipe-viewer#74]
There's an "AUR" for debian. https://mpr.makedeb.org/

I adapted the PKGBUILD for debian 11, it will probably work  in other variants.
pipe-viewer
[PKGBUILD.txt](https://github.com/trizen/pipe-viewer/files/9250043/PKGBUILD.txt)
lbry-viewer
[PKGBUILD-lbry.txt](https://github.com/trizen/pipe-viewer/files/9250119/PKGBUILD-lbry.txt)

I didn't publish it yet. Hum, how we go about this?

**Comment by trizen** [comment]
Please send a pull request.
