### ISSUE TITLE
[Request] When running from the cli, play the first result, then exit the application.

### ISSUE THREAD

**Issue by canisllup** [trizen/pipe-viewer#87]
Using one or two args.

**Comment by trizen** [comment]
Take a look at the `--std-input=s` option, combined with `--no-interactive`.

Example for searching for "numberphile", playing the first result, then exiting the app:

```console
pipe-viewer numberphile --std-input='1' --no-interactive
```

**Comment by canisllup** [comment]
Should have looked harder.

Thanks a bunch.
