### ISSUE TITLE
[minor] remove absolute paths for executables in config

### ISSUE THREAD

**Issue by ghost** [trizen/pipe-viewer#88]
/usr/local seams hardcoded in the code generating the config file. It's not a big deal, you can always edit it manually. It could be a difficulty for less sophisticated users.

I would propose to remove the absolute paths by default.

**Comment by trizen** [comment]
Absolute paths are used by default for better security when the user has `.` in their `$PATH` and they execute `pipe-viewer` in a folder that contains a malicious `ffmpeg` or `yt-dlp` executable, in which case `pipe-viewer` would execute the malicious executable. But when the absolute paths are specified, this security issue is mitigated.

See also: https://tldp.org/HOWTO/Path-12.html
