### ISSUE TITLE
audio only downloads a full video

### ISSUE THREAD

**Issue by pirate486743186** [trizen/pipe-viewer#9]
Why download a whole video (i'm guessing, max quality)
and not just download the audio file?
That's a very large waste of bandwidth.

**Comment by trizen** [comment]
I can't confirm this. Probably the video that you tried does not have audio in a separate file.

**Comment by pirate486743186** [comment]
interesting, youtube-dl -F list 251, (the best audio), but then there's nothing to download.... But the other audio only files are there. So, it still shouldn't download a video...

i hope you aren't sensitive XD
https://www.youtube.com/watch?v=6SVkgnTAXQo
